// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditEvents = `-- name: CountAuditEvents :one
SELECT count(*) FROM audit_events
`

func (q *Queries) CountAuditEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAuditEvent = `-- name: InsertAuditEvent :one
INSERT INTO audit_events (
    id, occurred_at, actor_kind, actor_user_id, actor_label,
    action, subject_type, subject_id, before, after, correlation_id, ip_prefix
) VALUES (
    $1, now(), $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, occurred_at
`

type InsertAuditEventParams struct {
	ID            uuid.UUID
	ActorKind     string
	ActorUserID   *uuid.UUID
	ActorLabel    *string
	Action        string
	SubjectType   string
	SubjectID     *string
	Before        []byte
	After         []byte
	CorrelationID *string
	IpPrefix      *string
}

type InsertAuditEventRow struct {
	ID         uuid.UUID
	OccurredAt pgtype.Timestamptz
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (InsertAuditEventRow, error) {
	row := q.db.QueryRow(ctx, insertAuditEvent,
		arg.ID,
		arg.ActorKind,
		arg.ActorUserID,
		arg.ActorLabel,
		arg.Action,
		arg.SubjectType,
		arg.SubjectID,
		arg.Before,
		arg.After,
		arg.CorrelationID,
		arg.IpPrefix,
	)
	var i InsertAuditEventRow
	err := row.Scan(&i.ID, &i.OccurredAt)
	return i, err
}
