// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const advisoryUnlock = `-- name: AdvisoryUnlock :one
SELECT pg_advisory_unlock($1::int, $2::int)
`

type AdvisoryUnlockParams struct {
	ClassID  int32
	ObjectID int32
}

func (q *Queries) AdvisoryUnlock(ctx context.Context, arg AdvisoryUnlockParams) (bool, error) {
	row := q.db.QueryRow(ctx, advisoryUnlock, arg.ClassID, arg.ObjectID)
	var pg_advisory_unlock bool
	err := row.Scan(&pg_advisory_unlock)
	return pg_advisory_unlock, err
}

const claimJob = `-- name: ClaimJob :one
UPDATE jobs
SET state        = 'leased',
    leased_by    = $1,
    leased_until = now() + $2::interval,
    attempts     = attempts + 1,
    updated_at   = now()
WHERE id = (
    SELECT id FROM jobs
    WHERE state = 'queued'
      AND run_after <= now()
      AND attempts < max_attempts
      AND kind = ANY($3::text[])
    ORDER BY priority, run_after
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, kind, payload, attempts, max_attempts, correlation_id, leased_until
`

type ClaimJobParams struct {
	LeasedBy      *string
	LeaseDuration pgtype.Interval
	Kinds         []string
}

type ClaimJobRow struct {
	ID            uuid.UUID
	Kind          string
	Payload       []byte
	Attempts      int32
	MaxAttempts   int32
	CorrelationID string
	LeasedUntil   pgtype.Timestamptz
}

// FOR UPDATE SKIP LOCKED: two workers never claim the same row, and a locked
// row never blocks the other worker's scan.
//
// `attempts` counts CLAIMS, not failures: it is incremented here, at claim
// time, so a worker that dies mid-job (OOM kill, SIGKILL, node eviction,
// libvips crash — ADR-004 expects all of these and has no boot blanket
// requeue) consumes one attempt. That is deliberate: it is the crash-loop
// brake, and without it a job that kills its worker every time is retried
// forever.
//
// `AND attempts < max_attempts` is what makes that safe. Without it, a row that
// had already burned its budget was still SELECTED — and then the UPDATE's
// `attempts + 1` violated jobs_attempts_bounded, the worker logged a transient
// claim failure and slept, and because the row sorts first by (priority,
// run_after) it was re-selected on the very next poll. One poisoned job stalled
// the entire site's queue and needed an operator with psql. The sweep below
// dead-letters such rows, so this predicate is the second half of that fix,
// not a way of hiding them.
func (q *Queries) ClaimJob(ctx context.Context, arg ClaimJobParams) (ClaimJobRow, error) {
	row := q.db.QueryRow(ctx, claimJob, arg.LeasedBy, arg.LeaseDuration, arg.Kinds)
	var i ClaimJobRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.Attempts,
		&i.MaxAttempts,
		&i.CorrelationID,
		&i.LeasedUntil,
	)
	return i, err
}

const completeJob = `-- name: CompleteJob :execrows
UPDATE jobs
SET state       = 'succeeded',
    finished_at = now(),
    updated_at  = now(),
    last_error  = NULL
WHERE id = $1 AND state = 'leased' AND leased_by = $2
`

type CompleteJobParams struct {
	ID       uuid.UUID
	LeasedBy *string
}

func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeJob, arg.ID, arg.LeasedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countStaleLeases = `-- name: CountStaleLeases :one
SELECT count(*)::bigint FROM jobs WHERE state = 'leased' AND leased_until < now()
`

func (q *Queries) CountStaleLeases(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countStaleLeases)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deadLetterJob = `-- name: DeadLetterJob :execrows
UPDATE jobs
SET state       = 'dead',
    last_error  = $1,
    finished_at = now(),
    leased_by   = NULL,
    leased_until = NULL,
    updated_at  = now()
WHERE id = $2 AND state = 'leased' AND leased_by = $3
`

type DeadLetterJobParams struct {
	LastError *string
	ID        uuid.UUID
	LeasedBy  *string
}

// attempts exhausted.
func (q *Queries) DeadLetterJob(ctx context.Context, arg DeadLetterJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, deadLetterJob, arg.LastError, arg.ID, arg.LeasedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueJob = `-- name: EnqueueJob :one

INSERT INTO jobs (
    id, kind, payload, idempotency_key, state, priority,
    attempts, max_attempts, run_after, correlation_id
) VALUES (
    $1, $2, $3, $4, 'queued', $5, 0, $6,
    COALESCE($7::timestamptz, now()), $8
)
ON CONFLICT DO NOTHING
RETURNING id, kind, state, run_after, created_at
`

type EnqueueJobParams struct {
	ID             uuid.UUID
	Kind           string
	Payload        []byte
	IdempotencyKey *string
	Priority       int16
	MaxAttempts    int32
	RunAfter       pgtype.Timestamptz
	CorrelationID  string
}

type EnqueueJobRow struct {
	ID        uuid.UUID
	Kind      string
	State     string
	RunAfter  pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

// Durable jobs (ADR-004). Every statement here is written so the invariant it
// protects is in the WHERE clause, not in the caller.
// ON CONFLICT DO NOTHING against the live-state partial unique index: a second
// enqueue of the same (kind, idempotency_key) while one is still queued or
// leased must return no row, so the caller can fetch the in-flight job instead
// of creating a duplicate.
//
// POSTGRESQL IS THE SINGLE CLOCK AUTHORITY. A NULL @run_after means "run now",
// and now() resolves it HERE, in the same transaction that stamps created_at.
// It must never be resolved in Go: ClaimJob's eligibility predicate is
// `run_after <= now()` against the DATABASE clock, so an application-side
// time.Now() compares two different clocks. When the database trails the
// application host — ordinary NTP skew between two containers, measured at
// ~1 ms locally and routinely far more in production — a job whose intent was
// "run now" is not claimable until the skew has elapsed, and a claim inside
// that window gets no rows on a queued, unleased row that is sitting right
// there. That was verifier FINDING V-1: two integration tests failed 3 runs in
// 20. A non-NULL @run_after is the caller's deliberate schedule and is stored
// verbatim, past or future.
func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (EnqueueJobRow, error) {
	row := q.db.QueryRow(ctx, enqueueJob,
		arg.ID,
		arg.Kind,
		arg.Payload,
		arg.IdempotencyKey,
		arg.Priority,
		arg.MaxAttempts,
		arg.RunAfter,
		arg.CorrelationID,
	)
	var i EnqueueJobRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.State,
		&i.RunAfter,
		&i.CreatedAt,
	)
	return i, err
}

const failJob = `-- name: FailJob :execrows
UPDATE jobs
SET state       = 'failed',
    last_error  = $1,
    finished_at = now(),
    leased_by   = NULL,
    leased_until = NULL,
    updated_at  = now()
WHERE id = $2 AND state = 'leased' AND leased_by = $3
`

type FailJobParams struct {
	LastError *string
	ID        uuid.UUID
	LeasedBy  *string
}

// A terminal error bypasses the retry ladder entirely.
func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, failJob, arg.LastError, arg.ID, arg.LeasedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getJob = `-- name: GetJob :one
SELECT id, kind, payload, idempotency_key, state, priority, attempts, max_attempts,
       run_after, leased_until, leased_by, last_error, correlation_id,
       created_at, updated_at, finished_at
FROM jobs
WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.IdempotencyKey,
		&i.State,
		&i.Priority,
		&i.Attempts,
		&i.MaxAttempts,
		&i.RunAfter,
		&i.LeasedUntil,
		&i.LeasedBy,
		&i.LastError,
		&i.CorrelationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getLiveJobByIdempotencyKey = `-- name: GetLiveJobByIdempotencyKey :one
SELECT id, kind, state, run_after, created_at
FROM jobs
WHERE kind = $1 AND idempotency_key = $2 AND state IN ('queued', 'leased')
`

type GetLiveJobByIdempotencyKeyParams struct {
	Kind           string
	IdempotencyKey *string
}

type GetLiveJobByIdempotencyKeyRow struct {
	ID        uuid.UUID
	Kind      string
	State     string
	RunAfter  pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetLiveJobByIdempotencyKey(ctx context.Context, arg GetLiveJobByIdempotencyKeyParams) (GetLiveJobByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getLiveJobByIdempotencyKey, arg.Kind, arg.IdempotencyKey)
	var i GetLiveJobByIdempotencyKeyRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.State,
		&i.RunAfter,
		&i.CreatedAt,
	)
	return i, err
}

const heartbeatJob = `-- name: HeartbeatJob :one
UPDATE jobs
SET leased_until = now() + $1::interval,
    updated_at   = now()
WHERE id = $2 AND state = 'leased' AND leased_by = $3
RETURNING id, leased_until
`

type HeartbeatJobParams struct {
	LeaseDuration pgtype.Interval
	ID            uuid.UUID
	LeasedBy      *string
}

type HeartbeatJobRow struct {
	ID          uuid.UUID
	LeasedUntil pgtype.Timestamptz
}

// Renewal is conditional on still holding the lease. A worker whose lease was
// swept must not be able to extend it and resume writing.
func (q *Queries) HeartbeatJob(ctx context.Context, arg HeartbeatJobParams) (HeartbeatJobRow, error) {
	row := q.db.QueryRow(ctx, heartbeatJob, arg.LeaseDuration, arg.ID, arg.LeasedBy)
	var i HeartbeatJobRow
	err := row.Scan(&i.ID, &i.LeasedUntil)
	return i, err
}

const jobDepthByKindState = `-- name: JobDepthByKindState :many
SELECT kind, state, count(*)::bigint AS depth
FROM jobs
WHERE state IN ('queued', 'leased')
GROUP BY kind, state
`

type JobDepthByKindStateRow struct {
	Kind  string
	State string
	Depth int64
}

func (q *Queries) JobDepthByKindState(ctx context.Context) ([]JobDepthByKindStateRow, error) {
	rows, err := q.db.Query(ctx, jobDepthByKindState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobDepthByKindStateRow{}
	for rows.Next() {
		var i JobDepthByKindStateRow
		if err := rows.Scan(&i.Kind, &i.State, &i.Depth); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oldestQueuedAgeByKind = `-- name: OldestQueuedAgeByKind :many
SELECT kind,
       EXTRACT(EPOCH FROM (now() - min(created_at)))::float8 AS oldest_age_seconds
FROM jobs
WHERE state = 'queued'
GROUP BY kind
`

type OldestQueuedAgeByKindRow struct {
	Kind             string
	OldestAgeSeconds float64
}

// Feeds vizra_jobs_oldest_queued_age_seconds, which readiness and doctor read
// against the Q-028 threshold.
func (q *Queries) OldestQueuedAgeByKind(ctx context.Context) ([]OldestQueuedAgeByKindRow, error) {
	rows, err := q.db.Query(ctx, oldestQueuedAgeByKind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OldestQueuedAgeByKindRow{}
	for rows.Next() {
		var i OldestQueuedAgeByKindRow
		if err := rows.Scan(&i.Kind, &i.OldestAgeSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retryJob = `-- name: RetryJob :execrows
UPDATE jobs
SET state      = 'queued',
    run_after  = now() + $1::interval,
    last_error = $2,
    leased_by  = NULL,
    leased_until = NULL,
    updated_at = now()
WHERE id = $3 AND state = 'leased' AND leased_by = $4
  AND attempts < max_attempts
`

type RetryJobParams struct {
	Backoff   pgtype.Interval
	LastError *string
	ID        uuid.UUID
	LeasedBy  *string
}

// A retryable failure with attempts left: back to queued, moved out along the
// ladder.
func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryJob,
		arg.Backoff,
		arg.LastError,
		arg.ID,
		arg.LeasedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sweepExpiredLeases = `-- name: SweepExpiredLeases :many
UPDATE jobs
SET state = CASE WHEN attempts >= max_attempts THEN 'dead' ELSE 'queued' END,
    last_error = CASE
        WHEN attempts >= max_attempts
        THEN 'lease elapsed with attempts exhausted: the worker holding this job stopped without recording an outcome'
        ELSE last_error
    END,
    finished_at  = CASE WHEN attempts >= max_attempts THEN now() ELSE NULL END,
    leased_by    = NULL,
    leased_until = NULL,
    updated_at   = now()
WHERE state = 'leased' AND leased_until < now()
RETURNING id, kind, attempts, state
`

type SweepExpiredLeasesRow struct {
	ID       uuid.UUID
	Kind     string
	Attempts int32
	State    string
}

// Reclaims rows whose lease has actually elapsed. There is no boot blanket
// requeue (ADR-004): this sweep, leader-gated, is the whole recovery mechanism.
//
// A row whose attempts are exhausted is DEAD-LETTERED rather than requeued.
// That is what ADR-004's "max_attempts exhaustion yields dead" means for the
// crash path: a worker that dies repeatedly burns the budget without any
// handler ever returning an error, so the retry path never sees it and only
// the sweep can declare it dead. Requeueing it instead left an unclaimable row
// at the head of the claim order forever.
//
// CONTRACT FOR ANY FUTURE REQUEUE OF A DEAD OR EXHAUSTED ROW — an M2
// `vizra jobs retry`, an admin "retry this job" control, a bulk replay:
// IT MUST RESET `attempts` TO 0 (or raise `max_attempts`) IN THE SAME
// STATEMENT that sets state back to 'queued'. Setting state alone recreates
// exactly the row this sweep exists to prevent: `state='queued' AND
// attempts >= max_attempts`, which ClaimJob's `AND attempts < max_attempts`
// can never take, and which the claim subselect nevertheless re-orders to the
// head of the queue on every poll. That is the unclaimable-but-queued zombie,
// and clearing it needs an operator with psql. The invariant is greppable:
//
//	SELECT count(*) FROM jobs WHERE state='queued' AND attempts>=max_attempts; -- must be 0
//
// `attempts` counts CLAIMS, so resetting it is the correct semantic for a
// deliberate human replay: the operator is granting a fresh budget, not
// pretending the earlier crashes never happened — last_error still records
// them. Written here rather than in a design note because this is the
// statement whoever writes that command will read.
// (Backend seat's carried-forward M2 note, PR #1 final closure.)
//
// One statement, so the two outcomes cannot diverge under concurrency.
func (q *Queries) SweepExpiredLeases(ctx context.Context) ([]SweepExpiredLeasesRow, error) {
	rows, err := q.db.Query(ctx, sweepExpiredLeases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SweepExpiredLeasesRow{}
	for rows.Next() {
		var i SweepExpiredLeasesRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Attempts,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tryAdvisoryLock = `-- name: TryAdvisoryLock :one
SELECT pg_try_advisory_lock($1::int, $2::int)
`

type TryAdvisoryLockParams struct {
	ClassID  int32
	ObjectID int32
}

// Leader election by a SESSION-scoped advisory lock in its TWO-INTEGER form, so
// it cannot collide with golang-migrate's single-bigint lock (ADR-004).
func (q *Queries) TryAdvisoryLock(ctx context.Context, arg TryAdvisoryLockParams) (bool, error) {
	row := q.db.QueryRow(ctx, tryAdvisoryLock, arg.ClassID, arg.ObjectID)
	var pg_try_advisory_lock bool
	err := row.Scan(&pg_try_advisory_lock)
	return pg_try_advisory_lock, err
}
