// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID            uuid.UUID
	OccurredAt    pgtype.Timestamptz
	ActorKind     string
	ActorUserID   *uuid.UUID
	ActorLabel    *string
	Action        string
	SubjectType   string
	SubjectID     *string
	Before        []byte
	After         []byte
	CorrelationID *string
	IpPrefix      *string
}

type Job struct {
	ID             uuid.UUID
	Kind           string
	Payload        []byte
	IdempotencyKey *string
	State          string
	Priority       int16
	Attempts       int32
	MaxAttempts    int32
	RunAfter       pgtype.Timestamptz
	LeasedUntil    pgtype.Timestamptz
	LeasedBy       *string
	LastError      *string
	CorrelationID  string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	FinishedAt     pgtype.Timestamptz
}

type Site struct {
	ID          uuid.UUID
	Handle      string
	BaseUrl     string
	PrivacyMode string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type StorageLocation struct {
	ID        uuid.UUID
	Handle    string
	Kind      string
	IsDefault bool
	ReadOnly  bool
	Config    []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
