// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: owner_claim.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const anyUserExists = `-- name: AnyUserExists :one

SELECT EXISTS (SELECT 1 FROM users) AS any_user
`

// Owner claim (VZ-INSTALL-003, migration 0005).
//
// The raw token never appears here: the service hashes the presented value and
// compares the digest in constant time in Go, then passes THE ROW'S OWN digest to
// ClaimOwner. Attacker-controlled bytes never reach SQL, so no index probe can
// become a timing oracle.
// The claim gate. "Unclaimed" is "no user rows at all", not "no owner row", so an
// instance that already has users is implicitly claimed and never mints again —
// and tombstoning the owner does not reopen the claim endpoint.
func (q *Queries) AnyUserExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, anyUserExists)
	var any_user bool
	err := row.Scan(&any_user)
	return any_user, err
}

const claimOwner = `-- name: ClaimOwner :one
WITH consumed AS (
    UPDATE owner_claim_tokens
       SET consumed_at = now()
     WHERE id
       AND token_sha256  = $1::bytea
       AND consumed_at   IS NULL
       AND superseded_at IS NULL
       AND expires_at    > now()
    RETURNING generation
),
owner AS (
    INSERT INTO users (id, username, email, role)
    SELECT $2::uuid,
           $3::text,
           $4::text,
           'owner'
      FROM consumed
    RETURNING id, username, role
),
cred AS (
    INSERT INTO credentials (id, user_id, kind, secret)
    SELECT $5::uuid,
           owner.id,
           'password',
           $6::text
      FROM owner
    RETURNING id
)
SELECT owner.id,
       owner.username,
       owner.role,
       (SELECT generation FROM consumed) AS token_generation
  FROM owner, cred
`

type ClaimOwnerParams struct {
	TokenSha256  []byte
	UserID       uuid.UUID
	Username     string
	Email        string
	CredentialID uuid.UUID
	PasswordHash string
}

type ClaimOwnerRow struct {
	ID              uuid.UUID
	Username        string
	Role            UserRole
	TokenGeneration int64
}

// Redeem the token and create THE owner plus its password credential, atomically.
//
// The guarded UPDATE must be the CTE the INSERT selects from. A data-modifying
// CTE always executes, so if the insert came first and the guarded update matched
// nothing, the owner row would still be written. `owner` selecting FROM consumed
// forces the redeem to produce a row before any user exists.
//
// Under READ COMMITTED (pinned explicitly on the transaction, never inherited
// from the server GUC) a losing concurrent claimer blocks on the row lock,
// re-evaluates `consumed_at IS NULL` against the committed row, matches nothing
// and returns no row. `users_one_owner` is the second, independent enforcer.
func (q *Queries) ClaimOwner(ctx context.Context, arg ClaimOwnerParams) (ClaimOwnerRow, error) {
	row := q.db.QueryRow(ctx, claimOwner,
		arg.TokenSha256,
		arg.UserID,
		arg.Username,
		arg.Email,
		arg.CredentialID,
		arg.PasswordHash,
	)
	var i ClaimOwnerRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.TokenGeneration,
	)
	return i, err
}

const getOwnerClaimToken = `-- name: GetOwnerClaimToken :one
SELECT token_sha256,
       generation,
       minted_at,
       expires_at,
       consumed_at,
       superseded_at,
       (consumed_at IS NULL AND superseded_at IS NULL AND expires_at > now()) AS live
  FROM owner_claim_tokens
 WHERE id
`

type GetOwnerClaimTokenRow struct {
	TokenSha256  []byte
	Generation   int64
	MintedAt     pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
	ConsumedAt   pgtype.Timestamptz
	SupersededAt pgtype.Timestamptz
	Live         *bool
}

// The single token row, if any. A plain fetch, never a lookup keyed by the
// presented value. `live` is computed with the DATABASE clock (ADR-004), so
// expiry is never decided by the application host.
func (q *Queries) GetOwnerClaimToken(ctx context.Context) (GetOwnerClaimTokenRow, error) {
	row := q.db.QueryRow(ctx, getOwnerClaimToken)
	var i GetOwnerClaimTokenRow
	err := row.Scan(
		&i.TokenSha256,
		&i.Generation,
		&i.MintedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.SupersededAt,
		&i.Live,
	)
	return i, err
}

const liveOwnerExists = `-- name: LiveOwnerExists :one
SELECT EXISTS (
    SELECT 1 FROM users WHERE role = 'owner' AND tombstoned_at IS NULL
) AS live_owner
`

// Used only to choose between 409 and 403 when ClaimOwner returns no row.
func (q *Queries) LiveOwnerExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, liveOwnerExists)
	var live_owner bool
	err := row.Scan(&live_owner)
	return live_owner, err
}

const mintOwnerClaimToken = `-- name: MintOwnerClaimToken :one
INSERT INTO owner_claim_tokens (id, token_sha256, generation, expires_at)
VALUES (true, $1::bytea, 1, now() + $2::interval)
ON CONFLICT (id) DO UPDATE
   SET token_sha256  = EXCLUDED.token_sha256,
       generation    = owner_claim_tokens.generation + 1,
       minted_at     = now(),
       expires_at    = now() + $2::interval,
       consumed_at   = NULL,
       superseded_at = NULL
RETURNING generation, minted_at, expires_at
`

type MintOwnerClaimTokenParams struct {
	TokenSha256 []byte
	Ttl         pgtype.Interval
}

type MintOwnerClaimTokenRow struct {
	Generation int64
	MintedAt   pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
}

// Mint or re-mint the single token row. Re-minting bumps the generation and
// clears both terminal columns, so exactly one token — the newest — is ever
// redeemable. Timestamps come from the database clock.
func (q *Queries) MintOwnerClaimToken(ctx context.Context, arg MintOwnerClaimTokenParams) (MintOwnerClaimTokenRow, error) {
	row := q.db.QueryRow(ctx, mintOwnerClaimToken, arg.TokenSha256, arg.Ttl)
	var i MintOwnerClaimTokenRow
	err := row.Scan(&i.Generation, &i.MintedAt, &i.ExpiresAt)
	return i, err
}

const supersedeLiveOwnerClaimToken = `-- name: SupersedeLiveOwnerClaimToken :execrows
UPDATE owner_claim_tokens
   SET superseded_at = now()
 WHERE id
   AND consumed_at   IS NULL
   AND superseded_at IS NULL
`

// Retire a live token without consuming it: used by `vizra claim-token` before it
// mints, and by boot when users already exist (an implicitly claimed instance
// must never hold a live owner-creating credential).
func (q *Queries) SupersedeLiveOwnerClaimToken(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, supersedeLiveOwnerClaimToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
