// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AdvisoryUnlock(ctx context.Context, arg AdvisoryUnlockParams) (bool, error)
	// FOR UPDATE SKIP LOCKED: two workers never claim the same row, and a locked
	// row never blocks the other worker's scan.
	ClaimJob(ctx context.Context, arg ClaimJobParams) (ClaimJobRow, error)
	CompleteJob(ctx context.Context, arg CompleteJobParams) (int64, error)
	CountAuditEvents(ctx context.Context) (int64, error)
	CountSites(ctx context.Context) (int64, error)
	CountStaleLeases(ctx context.Context) (int64, error)
	// attempts exhausted.
	DeadLetterJob(ctx context.Context, arg DeadLetterJobParams) (int64, error)
	// Durable jobs (ADR-004). Every statement here is written so the invariant it
	// protects is in the WHERE clause, not in the caller.
	// ON CONFLICT DO NOTHING against the live-state partial unique index: a second
	// enqueue of the same (kind, idempotency_key) while one is still queued or
	// leased must return no row, so the caller can fetch the in-flight job instead
	// of creating a duplicate.
	EnqueueJob(ctx context.Context, arg EnqueueJobParams) (EnqueueJobRow, error)
	// A terminal error bypasses the retry ladder entirely.
	FailJob(ctx context.Context, arg FailJobParams) (int64, error)
	// Core has exactly one site row (ADR-007). Ordering by handle makes the result
	// deterministic even if a future migration ever adds one.
	GetDefaultSite(ctx context.Context) (Site, error)
	GetDefaultStorageLocation(ctx context.Context) (StorageLocation, error)
	GetJob(ctx context.Context, id uuid.UUID) (Job, error)
	GetLiveJobByIdempotencyKey(ctx context.Context, arg GetLiveJobByIdempotencyKeyParams) (GetLiveJobByIdempotencyKeyRow, error)
	GetSiteByHandle(ctx context.Context, handle string) (Site, error)
	// Renewal is conditional on still holding the lease. A worker whose lease was
	// swept must not be able to extend it and resume writing.
	HeartbeatJob(ctx context.Context, arg HeartbeatJobParams) (HeartbeatJobRow, error)
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (InsertAuditEventRow, error)
	JobDepthByKindState(ctx context.Context) ([]JobDepthByKindStateRow, error)
	ListStorageLocations(ctx context.Context) ([]StorageLocation, error)
	// Feeds vizra_jobs_oldest_queued_age_seconds, which readiness and doctor read
	// against the Q-028 threshold.
	OldestQueuedAgeByKind(ctx context.Context) ([]OldestQueuedAgeByKindRow, error)
	// A retryable failure with attempts left: back to queued, moved out along the
	// ladder.
	RetryJob(ctx context.Context, arg RetryJobParams) (int64, error)
	// Reclaims ONLY rows whose lease has actually elapsed. There is no boot blanket
	// requeue (ADR-004): this sweep, leader-gated, is the whole recovery mechanism.
	SweepExpiredLeases(ctx context.Context) ([]SweepExpiredLeasesRow, error)
	// Leader election by a SESSION-scoped advisory lock in its TWO-INTEGER form, so
	// it cannot collide with golang-migrate's single-bigint lock (ADR-004).
	TryAdvisoryLock(ctx context.Context, arg TryAdvisoryLockParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
