// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AdvisoryUnlock(ctx context.Context, arg AdvisoryUnlockParams) (bool, error)
	// FOR UPDATE SKIP LOCKED: two workers never claim the same row, and a locked
	// row never blocks the other worker's scan.
	//
	// `attempts` counts CLAIMS, not failures: it is incremented here, at claim
	// time, so a worker that dies mid-job (OOM kill, SIGKILL, node eviction,
	// libvips crash — ADR-004 expects all of these and has no boot blanket
	// requeue) consumes one attempt. That is deliberate: it is the crash-loop
	// brake, and without it a job that kills its worker every time is retried
	// forever.
	//
	// `AND attempts < max_attempts` is what makes that safe. Without it, a row that
	// had already burned its budget was still SELECTED — and then the UPDATE's
	// `attempts + 1` violated jobs_attempts_bounded, the worker logged a transient
	// claim failure and slept, and because the row sorts first by (priority,
	// run_after) it was re-selected on the very next poll. One poisoned job stalled
	// the entire site's queue and needed an operator with psql. The sweep below
	// dead-letters such rows, so this predicate is the second half of that fix,
	// not a way of hiding them.
	ClaimJob(ctx context.Context, arg ClaimJobParams) (ClaimJobRow, error)
	CompleteJob(ctx context.Context, arg CompleteJobParams) (int64, error)
	CountAuditEvents(ctx context.Context) (int64, error)
	CountSites(ctx context.Context) (int64, error)
	CountStaleLeases(ctx context.Context) (int64, error)
	// attempts exhausted.
	DeadLetterJob(ctx context.Context, arg DeadLetterJobParams) (int64, error)
	// Durable jobs (ADR-004). Every statement here is written so the invariant it
	// protects is in the WHERE clause, not in the caller.
	// ON CONFLICT DO NOTHING against the live-state partial unique index: a second
	// enqueue of the same (kind, idempotency_key) while one is still queued or
	// leased must return no row, so the caller can fetch the in-flight job instead
	// of creating a duplicate.
	//
	// POSTGRESQL IS THE SINGLE CLOCK AUTHORITY. A NULL @run_after means "run now",
	// and now() resolves it HERE, in the same transaction that stamps created_at.
	// It must never be resolved in Go: ClaimJob's eligibility predicate is
	// `run_after <= now()` against the DATABASE clock, so an application-side
	// time.Now() compares two different clocks. When the database trails the
	// application host — ordinary NTP skew between two containers, measured at
	// ~1 ms locally and routinely far more in production — a job whose intent was
	// "run now" is not claimable until the skew has elapsed, and a claim inside
	// that window gets no rows on a queued, unleased row that is sitting right
	// there. That was verifier FINDING V-1: two integration tests failed 3 runs in
	// 20. A non-NULL @run_after is the caller's deliberate schedule and is stored
	// verbatim, past or future.
	EnqueueJob(ctx context.Context, arg EnqueueJobParams) (EnqueueJobRow, error)
	// A terminal error bypasses the retry ladder entirely.
	FailJob(ctx context.Context, arg FailJobParams) (int64, error)
	// Core has exactly one site row (ADR-007), enforced by the sites_singleton
	// unique index in migration 0001.
	//
	// No ORDER BY and no LIMIT, deliberately. An ORDER BY ... LIMIT 1 would make a
	// second row a SILENT wrong answer — whichever handle sorts first wins, and
	// `privacy_mode` is step (1) of the frozen precedence matrix, so a private site
	// could quietly start answering as a public one. Without the LIMIT, a second
	// row is a loud :one error at the first read. "Deterministic" is not the
	// property that matters here; "correct" is.
	GetDefaultSite(ctx context.Context) (Site, error)
	GetDefaultStorageLocation(ctx context.Context) (StorageLocation, error)
	GetJob(ctx context.Context, id uuid.UUID) (Job, error)
	GetLiveJobByIdempotencyKey(ctx context.Context, arg GetLiveJobByIdempotencyKeyParams) (GetLiveJobByIdempotencyKeyRow, error)
	GetSiteByHandle(ctx context.Context, handle string) (Site, error)
	// Renewal is conditional on still holding the lease. A worker whose lease was
	// swept must not be able to extend it and resume writing.
	HeartbeatJob(ctx context.Context, arg HeartbeatJobParams) (HeartbeatJobRow, error)
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (InsertAuditEventRow, error)
	JobDepthByKindState(ctx context.Context) ([]JobDepthByKindStateRow, error)
	ListStorageLocations(ctx context.Context) ([]StorageLocation, error)
	// Feeds vizra_jobs_oldest_queued_age_seconds, which readiness and doctor read
	// against the Q-028 threshold.
	OldestQueuedAgeByKind(ctx context.Context) ([]OldestQueuedAgeByKindRow, error)
	// A retryable failure with attempts left: back to queued, moved out along the
	// ladder.
	RetryJob(ctx context.Context, arg RetryJobParams) (int64, error)
	// Reclaims rows whose lease has actually elapsed. There is no boot blanket
	// requeue (ADR-004): this sweep, leader-gated, is the whole recovery mechanism.
	//
	// A row whose attempts are exhausted is DEAD-LETTERED rather than requeued.
	// That is what ADR-004's "max_attempts exhaustion yields dead" means for the
	// crash path: a worker that dies repeatedly burns the budget without any
	// handler ever returning an error, so the retry path never sees it and only
	// the sweep can declare it dead. Requeueing it instead left an unclaimable row
	// at the head of the claim order forever.
	//
	// CONTRACT FOR ANY FUTURE REQUEUE OF A DEAD OR EXHAUSTED ROW — an M2
	// `vizra jobs retry`, an admin "retry this job" control, a bulk replay:
	// IT MUST RESET `attempts` TO 0 (or raise `max_attempts`) IN THE SAME
	// STATEMENT that sets state back to 'queued'. Setting state alone recreates
	// exactly the row this sweep exists to prevent: `state='queued' AND
	// attempts >= max_attempts`, which ClaimJob's `AND attempts < max_attempts`
	// can never take, and which the claim subselect nevertheless re-orders to the
	// head of the queue on every poll. That is the unclaimable-but-queued zombie,
	// and clearing it needs an operator with psql. The invariant is greppable:
	//
	//   SELECT count(*) FROM jobs WHERE state='queued' AND attempts>=max_attempts; -- must be 0
	//
	// `attempts` counts CLAIMS, so resetting it is the correct semantic for a
	// deliberate human replay: the operator is granting a fresh budget, not
	// pretending the earlier crashes never happened — last_error still records
	// them. Written here rather than in a design note because this is the
	// statement whoever writes that command will read.
	// (Backend seat's carried-forward M2 note, PR #1 final closure.)
	//
	// One statement, so the two outcomes cannot diverge under concurrency.
	SweepExpiredLeases(ctx context.Context) ([]SweepExpiredLeasesRow, error)
	// Leader election by a SESSION-scoped advisory lock in its TWO-INTEGER form, so
	// it cannot collide with golang-migrate's single-bigint lock (ADR-004).
	TryAdvisoryLock(ctx context.Context, arg TryAdvisoryLockParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
