// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sites.sql

package sqlcgen

import (
	"context"
)

const countSites = `-- name: CountSites :one
SELECT count(*) FROM sites
`

func (q *Queries) CountSites(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSites)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDefaultSite = `-- name: GetDefaultSite :one
SELECT id, handle, base_url, privacy_mode, created_at, updated_at
FROM sites
ORDER BY handle
LIMIT 1
`

// Core has exactly one site row (ADR-007). Ordering by handle makes the result
// deterministic even if a future migration ever adds one.
func (q *Queries) GetDefaultSite(ctx context.Context) (Site, error) {
	row := q.db.QueryRow(ctx, getDefaultSite)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.BaseUrl,
		&i.PrivacyMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiteByHandle = `-- name: GetSiteByHandle :one
SELECT id, handle, base_url, privacy_mode, created_at, updated_at
FROM sites
WHERE handle = $1
`

func (q *Queries) GetSiteByHandle(ctx context.Context, handle string) (Site, error) {
	row := q.db.QueryRow(ctx, getSiteByHandle, handle)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.BaseUrl,
		&i.PrivacyMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
