// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sites.sql

package sqlcgen

import (
	"context"
)

const countSites = `-- name: CountSites :one
SELECT count(*) FROM sites
`

func (q *Queries) CountSites(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSites)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDefaultSite = `-- name: GetDefaultSite :one
SELECT id, handle, base_url, privacy_mode, created_at, updated_at
FROM sites
`

// Core has exactly one site row (ADR-007), enforced by the sites_singleton
// unique index in migration 0001.
//
// No ORDER BY and no LIMIT, deliberately. An ORDER BY ... LIMIT 1 would make a
// second row a SILENT wrong answer — whichever handle sorts first wins, and
// `privacy_mode` is step (1) of the frozen precedence matrix, so a private site
// could quietly start answering as a public one. Without the LIMIT, a second
// row is a loud :one error at the first read. "Deterministic" is not the
// property that matters here; "correct" is.
func (q *Queries) GetDefaultSite(ctx context.Context) (Site, error) {
	row := q.db.QueryRow(ctx, getDefaultSite)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.BaseUrl,
		&i.PrivacyMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiteByHandle = `-- name: GetSiteByHandle :one
SELECT id, handle, base_url, privacy_mode, created_at, updated_at
FROM sites
WHERE handle = $1
`

func (q *Queries) GetSiteByHandle(ctx context.Context, handle string) (Site, error) {
	row := q.db.QueryRow(ctx, getSiteByHandle, handle)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.BaseUrl,
		&i.PrivacyMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
