// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: storage.sql

package sqlcgen

import (
	"context"
)

const getDefaultStorageLocation = `-- name: GetDefaultStorageLocation :one
SELECT id, handle, kind, is_default, read_only, config, created_at, updated_at
FROM storage_locations
WHERE is_default
LIMIT 1
`

func (q *Queries) GetDefaultStorageLocation(ctx context.Context) (StorageLocation, error) {
	row := q.db.QueryRow(ctx, getDefaultStorageLocation)
	var i StorageLocation
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Kind,
		&i.IsDefault,
		&i.ReadOnly,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStorageLocations = `-- name: ListStorageLocations :many
SELECT id, handle, kind, is_default, read_only, config, created_at, updated_at
FROM storage_locations
ORDER BY handle
`

func (q *Queries) ListStorageLocations(ctx context.Context) ([]StorageLocation, error) {
	rows, err := q.db.Query(ctx, listStorageLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StorageLocation{}
	for rows.Next() {
		var i StorageLocation
		if err := rows.Scan(
			&i.ID,
			&i.Handle,
			&i.Kind,
			&i.IsDefault,
			&i.ReadOnly,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
