// Command fixturegen produces and verifies the M0 correctness fixture corpus
// (VZ-FOUND-007, ADR-009).
//
//	fixturegen generate    write the corpus into testdata/fixtures
//	fixturegen manifest    regenerate fixtures/manifest.json (re-pin)
//	fixturegen verify      regenerate into a scratch directory and compare
//	                       every byte against the committed manifest
//
// The load corpus is a different program: cmd/loadcorpusgen. They are kept
// apart on purpose (ADR-009 keeps the declared load corpus separate from the
// correctness corpus), so that no run can accidentally hash ten thousand
// generated photographs into the committed manifest.
package main

import (
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"github.com/yegamble/vizra-core/internal/fixtures"
)

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintf(os.Stderr, "fixturegen: %v\n", err)
		os.Exit(1)
	}
}

func run(args []string) error {
	fs := flag.NewFlagSet("fixturegen", flag.ContinueOnError)
	repo := fs.String("repo", ".", "repository root")
	scratch := fs.String("scratch", "", "directory to regenerate into for `verify` (default: a temporary directory)")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if fs.NArg() != 1 {
		fs.Usage()
		return errors.New("expected exactly one command: generate, manifest or verify")
	}
	root, err := filepath.Abs(*repo)
	if err != nil {
		return err
	}

	switch cmd := fs.Arg(0); cmd {
	case "generate":
		m, err := fixtures.Build(root)
		if err != nil {
			return err
		}
		fmt.Printf("generated %s into %s\n", m.Summary(), fixtures.OutputDir)
		for _, e := range m.Fixtures {
			fmt.Printf("  %-34s %8d  %s  %s\n", e.Path, e.Bytes, e.SHA256[:16], e.Tier)
		}
		return nil

	case "manifest":
		m, err := fixtures.Build(root)
		if err != nil {
			return err
		}
		if err := fixtures.WriteManifest(root, m); err != nil {
			return err
		}
		fmt.Printf("wrote %s: %s\n", fixtures.ManifestPath, m.Summary())
		fmt.Println("Review the diff: a changed fixture hash means the bytes every later media")
		fmt.Println("assertion is compared against have moved.")
		return nil

	case "verify":
		dir := *scratch
		if dir == "" {
			d, err := os.MkdirTemp("", "vizra-fixtures-verify-")
			if err != nil {
				return err
			}
			defer func() { _ = os.RemoveAll(d) }()
			dir = d
		}
		probs, err := fixtures.VerifyAgainstManifest(root, dir)
		if err != nil {
			return err
		}
		if len(probs) > 0 {
			fmt.Fprintf(os.Stderr, "fixtures-verify: FAILED with %d problem(s)\n\n", len(probs))
			for _, p := range probs {
				fmt.Fprintf(os.Stderr, "  %s\n      %s\n", p.Kind, p.Detail)
			}
			fmt.Fprintln(os.Stderr)
			return errors.New("the corpus does not match the committed manifest")
		}
		m, err := fixtures.ReadManifest(root)
		if err != nil {
			return err
		}
		fmt.Printf("fixtures-verify: ok — %s\n", m.Summary())
		fmt.Println("  every fixture regenerated byte-identically, the generator source digest matches,")
		fmt.Println("  the committed codec inputs match, and the toolchain is the pinned one.")
		return nil

	default:
		return fmt.Errorf("unknown command %q", cmd)
	}
}
