package fixtures

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
)

// ManifestPath is the committed manifest, relative to the repository root.
const ManifestPath = "fixtures/manifest.json"

// OutputDir is where the corpus is written. It is NOT committed: ADR-009
// commits "the manifest, with a sha256 per file and the generator version", and
// the corpus itself is what the pinned script produces. Committing generated
// bytes would also make the "reproduces byte-identically" claim untestable,
// because the committed copy would be the thing the check compared against.
const OutputDir = "testdata/fixtures"

// GeneratorSourceFiles are the files whose contents define the corpus. The
// manifest records a digest over them, so editing the generator without
// regenerating fails the lane — the same protection migrations/manifest.sha256
// gives the migration set.
//
// The embedded codec inputs are not listed here; they have their own entries in
// Manifest.CodecInputs.
var GeneratorSourceFiles = []string{
	"internal/fixtures/codec.go",
	"internal/fixtures/fixtures.go",
	"internal/fixtures/gif.go",
	"internal/fixtures/jpeg.go",
	"internal/fixtures/loadcorpus.go",
	"internal/fixtures/manifest.go",
	"internal/fixtures/mp4.go",
	"internal/fixtures/png.go",
	"internal/fixtures/raster.go",
	"internal/fixtures/webp.go",
	"cmd/fixturegen/main.go",
}

type FileInfo struct {
	SHA256 string `json:"sha256"`
	Bytes  int    `json:"bytes"`
}

type GeneratorInfo struct {
	Name         string   `json:"name"`
	Version      string   `json:"version"`
	SourceSHA256 string   `json:"source_sha256"`
	SourceFiles  []string `json:"source_files"`
}

type ToolchainInfo struct {
	// Go is the toolchain that ran the generator. compress/flate, image/jpeg,
	// image/gif and image/png are what write the bytes, and they are stable in
	// practice but not contractually frozen across Go releases. The verifier
	// refuses to compare against a manifest made by another toolchain, rather
	// than reporting a difference it cannot explain.
	Go string `json:"go"`
	// GoMod is go.mod's `go` directive — the module's LANGUAGE version, which
	// sets the GODEBUG compatibility defaults the standard library runs under.
	//
	// This is not a theoretical pin. Building this exact generator source with
	// the same go1.27.1 toolchain under `go 1.26.0` and under `go 1.26.2`
	// produces DIFFERENT deflate output and therefore different PNG bytes;
	// that is how the discrepancy that first broke this corpus was found
	// (docs/evidence/fixtures/2026-09-21-determinism.md). Pinning the toolchain
	// alone would have left a way for the corpus to move with a green lane.
	GoMod string `json:"go_mod_language_version"`
}

// goDirective reads the `go` line from go.mod. A three-line parser rather than
// a module-parsing dependency: the value is one token on one line.
func goDirective(repoRoot string) (string, error) {
	b, err := os.ReadFile(filepath.Join(repoRoot, "go.mod"))
	if err != nil {
		return "", err
	}
	for _, line := range strings.Split(string(b), "\n") {
		if f := strings.Fields(line); len(f) == 2 && f[0] == "go" {
			return f[1], nil
		}
	}
	return "", fmt.Errorf("no `go` directive in go.mod")
}

type Entry struct {
	ID      string   `json:"id"`
	Path    string   `json:"path"`
	Format  string   `json:"format"`
	Tier    Tier     `json:"tier"`
	ADR009  int      `json:"adr009_item"`
	SHA256  string   `json:"sha256"`
	Bytes   int      `json:"bytes"`
	Width   int      `json:"width"`
	Height  int      `json:"height"`
	Decode  Decode   `json:"expected_decode"`
	Purpose string   `json:"purpose"`
	Asserts []string `json:"asserts"`
	License string   `json:"license"`
}

type Manifest struct {
	Schema      int           `json:"schema"`
	Note        string        `json:"note"`
	Generator   GeneratorInfo `json:"generator"`
	Toolchain   ToolchainInfo `json:"toolchain"`
	OutputDir   string        `json:"output_dir"`
	CodecInputs []CodecOrigin `json:"codec_inputs"`
	Fixtures    []Entry       `json:"fixtures"`
}

const manifestNote = "VZ-FOUND-007 / ADR-009. Generated by `make fixtures-manifest`; verified by `make fixtures-verify`. " +
	"The corpus itself is NOT committed: this manifest is the committed artefact and the generator reproduces the bytes."

func sha256Hex(b []byte) string {
	sum := sha256.Sum256(b)
	return hex.EncodeToString(sum[:])
}

// SourceDigest hashes the generator's own source, path and contents, in the
// fixed order of GeneratorSourceFiles.
func SourceDigest(repoRoot string) (string, error) {
	h := sha256.New()
	for _, rel := range GeneratorSourceFiles {
		b, err := os.ReadFile(filepath.Join(repoRoot, filepath.FromSlash(rel)))
		if err != nil {
			return "", fmt.Errorf("generator source %s: %w", rel, err)
		}
		fmt.Fprintf(h, "%s\n%d\n", rel, len(b))
		h.Write(b)
	}
	return hex.EncodeToString(h.Sum(nil)), nil
}

// Build generates the corpus into repoRoot/OutputDir and returns the manifest
// that describes what it produced.
func Build(repoRoot string) (*Manifest, error) {
	digest, err := SourceDigest(repoRoot)
	if err != nil {
		return nil, err
	}
	goMod, err := goDirective(repoRoot)
	if err != nil {
		return nil, err
	}
	out := filepath.Join(repoRoot, filepath.FromSlash(OutputDir))
	files, err := Generate(out)
	if err != nil {
		return nil, err
	}
	m := &Manifest{
		Schema:    1,
		Note:      manifestNote,
		OutputDir: OutputDir,
		Generator: GeneratorInfo{
			Name: "fixturegen", Version: Version,
			SourceSHA256: digest, SourceFiles: GeneratorSourceFiles,
		},
		Toolchain: ToolchainInfo{Go: runtime.Version(), GoMod: goMod},
	}
	for _, o := range CodecInputs() {
		b, err := os.ReadFile(filepath.Join(repoRoot, filepath.FromSlash(o.Path)))
		if err != nil {
			return nil, err
		}
		o.SHA256, o.Bytes = sha256Hex(b), len(b)
		m.CodecInputs = append(m.CodecInputs, o)
	}
	for _, s := range Corpus() {
		fi, ok := files[s.Path]
		if !ok {
			return nil, fmt.Errorf("generator produced no %s", s.Path)
		}
		m.Fixtures = append(m.Fixtures, Entry{
			ID: s.ID, Path: s.Path, Format: s.Format, Tier: s.Tier, ADR009: s.ADR009,
			SHA256: fi.SHA256, Bytes: fi.Bytes,
			Width: s.Width, Height: s.Height, Decode: s.Decode,
			Purpose: s.Purpose, Asserts: s.Asserts, License: s.License,
		})
	}
	return m, nil
}

// WriteManifest writes the manifest as stable, diffable JSON.
func WriteManifest(repoRoot string, m *Manifest) error {
	b, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		return err
	}
	b = append(b, '\n')
	p := filepath.Join(repoRoot, filepath.FromSlash(ManifestPath))
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		return err
	}
	return os.WriteFile(p, b, 0o644)
}

func ReadManifest(repoRoot string) (*Manifest, error) {
	b, err := os.ReadFile(filepath.Join(repoRoot, filepath.FromSlash(ManifestPath)))
	if err != nil {
		return nil, err
	}
	var m Manifest
	if err := json.Unmarshal(b, &m); err != nil {
		return nil, fmt.Errorf("%s is not valid JSON: %w", ManifestPath, err)
	}
	return &m, nil
}

// Problem is one named failure. Every check reports the file or pin it is
// about, because "fixtures-verify failed" on its own tells a reader nothing.
type Problem struct {
	Kind   string
	Detail string
}

func (p Problem) String() string { return p.Kind + ": " + p.Detail }

// VerifyAgainstManifest regenerates the corpus into a scratch directory and
// compares everything the manifest pins. It returns every problem it finds
// rather than the first, so one run names all the drift.
func VerifyAgainstManifest(repoRoot, scratch string) ([]Problem, error) {
	m, err := ReadManifest(repoRoot)
	if err != nil {
		return nil, err
	}
	var probs []Problem

	// 1. The pinned toolchain. A different Go release can change what
	//    compress/flate and image/jpeg emit, so a comparison made under one is
	//    not evidence about the other.
	if got := runtime.Version(); got != m.Toolchain.Go {
		probs = append(probs, Problem{
			Kind: "toolchain-pin",
			Detail: fmt.Sprintf("the manifest was produced with %s, this toolchain is %s. "+
				"A byte comparison across Go releases proves nothing; build with the pinned toolchain, "+
				"or re-pin deliberately with `make fixtures-manifest`.", m.Toolchain.Go, got),
		})
	}

	goMod, err := goDirective(repoRoot)
	if err != nil {
		return nil, err
	}
	if goMod != m.Toolchain.GoMod {
		probs = append(probs, Problem{
			Kind: "toolchain-pin",
			Detail: fmt.Sprintf("go.mod's language version is %s, the manifest records %s. "+
				"That directive sets the GODEBUG compatibility defaults the standard library encoders run under, "+
				"and it demonstrably changes the deflate output: re-pin with `make fixtures-manifest` and review "+
				"which fixture hashes moved.", goMod, m.Toolchain.GoMod),
		})
	}

	// 2. The generator's own source.
	digest, err := SourceDigest(repoRoot)
	if err != nil {
		return nil, err
	}
	if digest != m.Generator.SourceSHA256 {
		probs = append(probs, Problem{
			Kind: "generator-source",
			Detail: fmt.Sprintf("the generator source digest is %s, the manifest records %s. "+
				"The generator changed and the manifest was not regenerated: run `make fixtures-manifest` "+
				"and review the fixture hashes in the diff.", digest[:16]+"…", m.Generator.SourceSHA256[:16]+"…"),
		})
	}
	if m.Generator.Version != Version {
		probs = append(probs, Problem{
			Kind:   "generator-version",
			Detail: fmt.Sprintf("the manifest records generator version %q, this generator is %q", m.Generator.Version, Version),
		})
	}
	if !equalStrings(m.Generator.SourceFiles, GeneratorSourceFiles) {
		probs = append(probs, Problem{
			Kind:   "generator-source-list",
			Detail: "the manifest's source_files list differs from GeneratorSourceFiles; a file added to the generator and not to that list is not covered by the digest",
		})
	}

	// 3. The committed codec inputs.
	want := map[string]CodecOrigin{}
	for _, o := range m.CodecInputs {
		want[o.Path] = o
	}
	for _, o := range CodecInputs() {
		rec, ok := want[o.Path]
		if !ok {
			probs = append(probs, Problem{Kind: "codec-input", Detail: o.Path + " is not in the manifest"})
			continue
		}
		b, err := os.ReadFile(filepath.Join(repoRoot, filepath.FromSlash(o.Path)))
		if err != nil {
			probs = append(probs, Problem{Kind: "codec-input", Detail: fmt.Sprintf("%s: %v", o.Path, err)})
			continue
		}
		if got := sha256Hex(b); got != rec.SHA256 {
			probs = append(probs, Problem{
				Kind:   "codec-input",
				Detail: fmt.Sprintf("%s has sha256 %s, the manifest records %s", o.Path, got, rec.SHA256),
			})
		}
		if rec.ToolVersion != o.ToolVersion {
			probs = append(probs, Problem{
				Kind: "codec-tool-pin",
				Detail: fmt.Sprintf("%s was produced by %q, the manifest records %q. "+
					"A codec pin moved without the corpus being re-pinned.", o.Path, o.ToolVersion, rec.ToolVersion),
			})
		}
		delete(want, o.Path)
	}
	for p := range want {
		probs = append(probs, Problem{Kind: "codec-input", Detail: "the manifest records " + p + ", which the generator no longer uses"})
	}

	// 4. The corpus on disk, if it is there, must be the corpus the
	//    manifest describes — a stale or hand-edited testdata tree is exactly
	//    what turns a later media assertion into a false pass.
	outDir := filepath.Join(repoRoot, filepath.FromSlash(OutputDir))
	for _, e := range m.Fixtures {
		b, err := os.ReadFile(filepath.Join(outDir, e.Path))
		if os.IsNotExist(err) {
			continue // not generated yet in this checkout; step 4 already compared
		}
		if err != nil {
			probs = append(probs, Problem{Kind: "fixture-on-disk", Detail: fmt.Sprintf("%s: %v", e.Path, err)})
			continue
		}
		if got := sha256Hex(b); got != e.SHA256 {
			probs = append(probs, Problem{
				Kind: "fixture-on-disk",
				Detail: fmt.Sprintf("%s in %s has sha256 %s, the manifest records %s — the corpus on disk is not the corpus the manifest describes",
					e.Path, OutputDir, got, e.SHA256),
			})
		}
	}

	// Everything so far was cheap. Regenerating the corpus is not — it is tens
	// of seconds under the race detector — so if anything above already
	// disagrees, stop and say so rather than spending that time producing a
	// dozen "fixture bytes differ" lines whose real cause is the one line
	// already reported.
	if len(probs) > 0 {
		probs = append(probs, Problem{
			Kind: "not-compared",
			Detail: "the fixture bytes were NOT regenerated and compared, because something cheaper already disagrees with the manifest. " +
				"Fix the problems above and run again; a byte comparison made under a different pin, a different generator source or " +
				"beside a stale corpus is not evidence about anything.",
		})
		sortProblems(probs)
		return probs, nil
	}

	// 5. Regenerate and compare, byte for byte.
	files, err := Generate(scratch)
	if err != nil {
		return nil, err
	}
	recorded := map[string]Entry{}
	for _, e := range m.Fixtures {
		recorded[e.Path] = e
	}
	for _, s := range Corpus() {
		e, ok := recorded[s.Path]
		if !ok {
			probs = append(probs, Problem{Kind: "fixture-missing-from-manifest", Detail: s.Path})
			continue
		}
		got := files[s.Path]
		if got.SHA256 != e.SHA256 {
			probs = append(probs, Problem{
				Kind: "fixture-bytes",
				Detail: fmt.Sprintf("%s: regenerated sha256 %s (%d bytes), the manifest records %s (%d bytes)",
					s.Path, got.SHA256, got.Bytes, e.SHA256, e.Bytes),
			})
		}
		delete(recorded, s.Path)
	}
	for p := range recorded {
		probs = append(probs, Problem{Kind: "fixture-not-generated", Detail: "the manifest records " + p + ", which the generator does not produce"})
	}

	sortProblems(probs)
	return probs, nil
}

func sortProblems(probs []Problem) {
	sort.Slice(probs, func(i, j int) bool {
		if probs[i].Kind != probs[j].Kind {
			return probs[i].Kind < probs[j].Kind
		}
		return probs[i].Detail < probs[j].Detail
	})
}

func equalStrings(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// Summary is a short human-readable description of the corpus, for the CLI.
func (m *Manifest) Summary() string {
	var sb strings.Builder
	var total int
	for _, e := range m.Fixtures {
		total += e.Bytes
	}
	fmt.Fprintf(&sb, "%d fixtures, %d bytes, generator %s (%s), toolchain %s",
		len(m.Fixtures), total, m.Generator.Version, m.Generator.SourceSHA256[:12], m.Toolchain.Go)
	return sb.String()
}
